prop_replace () {
  target_file=${3}
  echo 'replacing target file ' ${target_file}
  sed -i -e "s|^$1=.*$|$1=$2|"  ${target_file}
}

# Install the jq tool. This tool is needed to query values from the config.json
# file created by the tls-toolkit running in the client mode
apt-get update && apt-get install jq -y

# Run the tls-toolkit in client mode to generate the truststore and keystore
/opt/nifi/nifi-toolkit-current/bin/tls-toolkit.sh client -c my-nifi-rs -t Welcome2018nifihdf3 --dn "CN=$(hostname -f), OU=NIFI" --subjectAlternativeNames localhost

# Use jq to extract the passwords form the config.json generated by the tls-toolkit
KEY_STORE_PASSWD=`jq -r '.keyStorePassword' ./config.json`
KEY_PASSWD=`jq -r '.keyPassword' ./config.json`
TRUST_STORE_PASSWD=`jq -r '.trustStorePassword' ./config.json`

# Move the truststore and keystore in the conf directory
mv ./keystore.jks conf/
mv ./truststore.jks conf/

# Setup variables to point to files
NIFI_HOME=/opt/nifi/nifi-current
NIFI_PROPS=${NIFI_HOME}/conf/nifi.properties

NIFI_HOME=/opt/nifi/nifi-current
NIFI_AUTHZ_FILE=${NIFI_HOME}/conf/authorizers.xml
NIFI_IS_CLUSTER=true
NIFI_HTTP_PORT=""
NIFI_HTTPS_PORT=8443
NIFI_PROXY_CONTEXT_PATH=/
NIFI_PROXY_HOST=localhost:9443
NIFI_KEY_STORE=./conf/keystore.jks
NIFI_KEY_STORE_TYPE=jks
NIFI_KEY_STORE_PASSWORD=$KEY_STORE_PASSWD
NIFI_KEY_PASSWORD=$KEY_PASSWD
NIFI_TRUST_STORE=./conf/truststore.jks
NIFI_TRUST_STORE_TYPE=jks
NIFI_TRUST_STORE_PASSWORD=$TRUST_STORE_PASSWD

# Configure nifi.properties
prop_replace nifi.cluster.node.address              ${NIFI_CLUSTER_ADDRESS}         ${NIFI_PROPS}
prop_replace nifi.cluster.is.node                   ${NIFI_IS_CLUSTER}              ${NIFI_PROPS}
prop_replace nifi.cluster.protocol.is.secure        true                            ${NIFI_PROPS}
prop_replace nifi.cluster.node.protocol.port        7474                            ${NIFI_PROPS}
prop_replace nifi.web.http.port                     ''                              ${NIFI_PROPS}
prop_replace nifi.web.https.port                    ${NIFI_HTTPS_PORT}              ${NIFI_PROPS}
prop_replace nifi.web.https.host                    ${NIFI_CLUSTER_ADDRESS}         ${NIFI_PROPS}
prop_replace nifi.remote.input.secure               true                            ${NIFI_PROPS}
prop_replace nifi.web.proxy.context.path            ${NIFI_PROXY_CONTEXT_PATH}      ${NIFI_PROPS}
prop_replace nifi.web.proxy.host                    ${NIFI_PROXY_HOST}              ${NIFI_PROPS}
prop_replace nifi.security.keystore                 ${NIFI_KEY_STORE}               ${NIFI_PROPS}
prop_replace nifi.security.keystoreType             ${NIFI_KEY_STORE_TYPE}          ${NIFI_PROPS}
prop_replace nifi.security.keystorePasswd           ${NIFI_KEY_STORE_PASSWORD}      ${NIFI_PROPS}
prop_replace nifi.security.keyPasswd                ${NIFI_KEY_PASSWORD}            ${NIFI_PROPS}
prop_replace nifi.security.truststore               ${NIFI_TRUST_STORE}             ${NIFI_PROPS}
prop_replace nifi.security.truststoreType           ${NIFI_TRUST_STORE_TYPE}        ${NIFI_PROPS}
prop_replace nifi.security.truststorePasswd         ${NIFI_TRUST_STORE_PASSWORD}    ${NIFI_PROPS}